$	ON WARNING THEN $GOTO END
$	UIC JOUST
$!	DOWN DMA1:[PFUT.JOUST]T12	!IMMATATION $F000 ROM
$	DOWN DMA1:[PFUT.JOUST]JOUSTI
$	DOWN DMA1:[PFUT.JOUST]TB12
$	DOWN DMA1:[PFUT.JOUST]MESSAGE
$	DOWN DMA1:[PFUT.JOUST]ATT
$	DOWN DMA1:[PFUT.JOUST]SYSTEM
$	DOWN DMA1:[PFUT.JOUST]JOUST
$END:	
